$$
\newcommand{\ped}[1]{_{\mathrm{#1}}}
\newcommand{\ap}[1]{^{\mathrm{#1}}}
\newcommand{\nvector}[1]{\mathbf{#1}}
\newcommand{\nmatrix}[1]{\mathit{#1}}
\newcommand{\unitvector}[1]{\hat{\nvector{e}}_{#1}}
\newcommand{\volume}{\mathcal{V}}
\newcommand{\average}[1]{\overline{#1}}
\newcommand{\rate}[1]{\dot{#1}}
\newcommand{\flux}[1]{{#1}''}
\newcommand{\curl}[1]{\nabla\times {#1}}
\newcommand{\curlv}[1]{\curl{\nvector{#1}}}
\newcommand{\divergent}[1]{\nabla \cdot #1}
\newcommand{\divergentv}[1]{\divergent{\nvector{#1}}}
\newcommand{\divergentpar}[1]{\divergent{\left( #1 \right)}}
\newcommand{\gradient}[1]{\nabla {#1}}
\newcommand{\gradientpar}[1]{\gradient{\left( {#1} \right)}}
\newcommand{\laplacian}[1]{\nabla^2 #1}
\newcommand{\laplacianpar}[1]{\laplacian{\left( #1 \right)}}
\newcommand{\vectornorm}[1]{\left\lVert #1 \right\rVert}
\newcommand{\diffp}[2]{\frac{\partial {#1}}{\partial {#2}}}
\newcommand{\diffps}[2]{\frac{\partial^2 {#1}}{\partial {#2}^2}}
\newcommand{\rvec}{\nvector{r}}
\newcommand{\nvh}{\nvector{H}}
\newcommand{\nvb}{\nvector{B}}
\newcommand{\nvrem}{\nvector{B}\ped{rem}}
\newcommand{\nvbrem}{\nvrem}
\newcommand{\nvm}{\nvector{M}}
\newcommand{\mur}{\mu\ped{r}}
\newcommand{\nvbremhat}{\hat{\nvector{B}}\ped{rem}}
\newcommand{\acoef}[2]{a_{{#1},\mathrm{#2}}}
\newcommand{\bcoef}[2]{b_{{#1},\mathrm{#2}}}
\newcommand{\Azexpr}[1]{A_{\mathrm{#1}\, z}}
\newcommand{\bremii}{B_{\mathrm{rem,II}}}
\newcommand{\bremiv}{B_{\mathrm{rem,IV}}}
\newcommand{\aIII}{\acoef{1}{III}}
\newcommand{\bIII}{\bcoef{1}{III}}
\newcommand{\nvbIII}{\nvector{B}\ped{III}}
\newcommand{\BIII}{B\ped{III}}
\newcommand{\diffd}[1]{\mathrm{d}\,{#1}}
$$

# TeslaMax Optimization

Teslamax model:

<img src="figures/teslamax.png" width=500>

In [1]:
from pathlib import Path
import os
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import teslamax
from teslamax import TeslaMaxModel



mpl_params = {'text.usetex': True,
              'font.family': 'serif',
              'font.serif': 'Computer Modern',
              'text.latex.preamble': [r'\usepackage{engsymbols}',
                                      r'\usepackage{magref}',
                                      r'\usepackage{siunitx}']}
matplotlib.rcParams.update(mpl_params)


In [2]:
os.chdir('C:\\Users\\fabiofortkamp\\code\\TeslaMax\\')

In [3]:
os.getcwd()

'C:\\Users\\fabiofortkamp\\code\\TeslaMax'

In [ ]:
import importlib
importlib.reload(teslamax)

## Calculating functional

In [4]:
params_optimization = {"R_i": 0.015,
                "R_o": 0.070,
                "h_gap": 0.020,
                "R_s": 0.140,
                "h_fc": 0.010,
                "R_e": 2,
                "n_IV": 3,
                "phi_S_IV": 45,
                "n_II": 3,
                "phi_C_II": 15,
                "phi_S_II": 45,
                "B_rem_II_1": 1.4,
                "B_rem_II_2": 1.4,
                "B_rem_II_3": 1.4,
                "mu_r_II": 1.05,
                "B_rem_IV_1": 1.4,
                "B_rem_IV_2": 1.4,
                "B_rem_IV_3": 1.4,
                "mu_r_IV": 1.05,
              "linear_iron": 1,
              "mu_r_iron": 5e3,
             }

alpha_B_rem_0 = [15,30,45,15,45,135]

params_optimization = teslamax.expand_parameters_from_remanence_array(alpha_B_rem_0, params_optimization)

The code below calculate the individual contributions for each magnet block. For instance, the i-th element of the variable `F_II_x` is a list of points in the form $(B_x, B_y)$, calculated in a mesh in the air gap, where only the i-th segment in magnet II has a non-null remanence, with magnitude included in the above dictionary and oriented in the $x$ direction.

In [5]:
def calculate_F_operators(points, params):
    """
    Return (F_II_x, F_II_y, F_IV_x, F_IV_y), where each element is a list of the F-operators vector fields
    calculated at points.
    
    For instance, F_II_x[0] is an array of (B_x, B_y), calculated when only the first segment of magnet II
    is magnetized in the x-direction, with unit remanence
    """
    
    n_II = params['n_II']
    n_IV = params['n_IV']
        
    F_II_x = []
    F_II_y = []
    
    F_IV_x = []
    F_IV_y = []
    
    for k in range(0,n_II):
        F_II_x.append(teslamax.calculate_B_III_from_single_block(point=points, 
                                                   segment=k+1, 
                                                   magnet='II', 
                                                   magnitude=1.0, 
                                                    angle=0.0, 
                                                    params=params))
        
        
        F_II_y.append(teslamax.calculate_B_III_from_single_block(point=points, 
                                                   segment=k+1,
                                                   magnet='II', 
                                                   magnitude=1.0, 
                                                    angle=90.0, 
                                                    params=params))

    for j in range(0,n_IV):
        F_IV_x.append(teslamax.calculate_B_III_from_single_block(point=points, 
                                                   segment=j+1, 
                                                   magnet='IV', 
                                                   magnitude=1.0, 
                                                    angle=0.0, 
                                                    params=params))
        
        
        F_IV_y.append(teslamax.calculate_B_III_from_single_block(point=points, 
                                                   segment=j+1,
                                                   magnet='IV', 
                                                   magnitude=1.0, 
                                                    angle=90.0, 
                                                    params=params))
        
    return (F_II_x, F_II_y, F_IV_x, F_IV_y)

In [7]:
%%time

R_o = params_optimization["R_o"]
R_g = params_optimization["R_o"] + params_optimization["h_gap"]
points_air_gap = teslamax.generate_sector_mesh_points(1.001*R_o,0.999*R_g,0.0,np.pi)

F_II_x, F_II_y, F_IV_x, F_IV_y = calculate_F_operators(points_air_gap, params_optimization)

Wall time: 6min 21s


In [8]:
F_IV_x[0]

array([[  5.62432887e-01,   1.05041663e-03],
       [  5.61311074e-01,   5.05399649e-03],
       [  5.60215283e-01,   9.26271274e-03],
       ..., 
       [  5.55988536e-01,   3.01955227e-03],
       [  5.55688688e-01,   1.45630145e-03],
       [  5.55408745e-01,  -1.23346284e-04]])

Next we apply the principle of superposition, combining the contributions calculated above and using the actual remanence magnitude and angle as specified by the dictionary `params_optimization` and by the array `alpha_B_rem`.

In [9]:
def superposition_B_III(points, F_II_x, F_II_y, F_IV_x, F_IV_y, alpha_B_rem, params):
    """
    Return (x, y, B_x, B_y) based on the lists of F-operators and a vector of remanence angles.
    
    - 'points' is a list of (x,y) points where all of the F-operators are calculated.
    - Each element of 'F_{magnet}_{direction}' is an array of (B_x, B_y) vectors calculated at 'points', 
    considering only the effect of that segment
    - 'alpha_B_rem' is a vector of (n_II + n_IV) remanences, where the first n_II represent magnet II and
    the remaining elements represent magnet IV
    - 'params' is a dictionary of parameters
    
    """
    
    B_III = 0

    n_II = params["n_II"]
    for k in range(0,n_II):
        B_rem = params["B_rem_II_%d" %(k+1)]
        alpha = np.deg2rad(alpha_B_rem[k])
    
        B = B_rem * (np.cos(alpha) * F_II_x[k] + np.sin(alpha) * F_II_y[k])
    
        B_III = B_III + B
    
    n_IV = params["n_IV"]
    for j in range(0,n_IV):
        B_rem = params["B_rem_IV_%d" %(j+1)]
        alpha = np.deg2rad(alpha_B_rem[n_II + j])
        
        B = B_rem * (np.cos(alpha) * F_IV_x[j] + np.sin(alpha) * F_IV_y[j])
        
        B_III = B_III + B
        
    B_III_grid = np.concatenate((points, B_III), axis=1)
    
    return B_III_grid

In [10]:
B_III_data = superposition_B_III(points_air_gap, F_II_x, F_II_y, F_IV_x, F_IV_y, alpha_B_rem_0, params_optimization)

tmm = TeslaMaxModel(params_optimization, 'teslamax-play')
tmm.run()

B_III_data_tmm = np.concatenate((points_air_gap,tmm.calculate_B_III_from_position(points_air_gap)),axis=1)

In [11]:
B_III_data

array([[  7.00700000e-02,   0.00000000e+00,   1.22242526e+00,
          1.56684323e-03],
       [  7.00678280e-02,   5.51702062e-04,   1.22074317e+00,
          1.05617420e-02],
       [  7.00613123e-02,   1.10336992e-03,   1.21912067e+00,
          1.98656516e-02],
       ..., 
       [ -8.98988524e-02,   1.41578407e-03,   1.22330154e+00,
          1.19281218e-01],
       [ -8.99072130e-02,   7.07913977e-04,   1.25830943e+00,
          1.25478166e-01],
       [ -8.99100000e-02,   1.10107994e-17,   1.29072077e+00,
          1.30759901e-01]])

In [12]:
B_III_data_tmm

array([[  7.00700000e-02,   0.00000000e+00,   1.22085614e+00,
          1.56976336e-03],
       [  7.00678280e-02,   5.51702062e-04,   1.21917075e+00,
          1.05510198e-02],
       [  7.00613123e-02,   1.10336992e-03,   1.21754479e+00,
          1.98418276e-02],
       ..., 
       [ -8.98988524e-02,   1.41578407e-03,   1.22092052e+00,
          1.19359763e-01],
       [ -8.99072130e-02,   7.07913977e-04,   1.25592566e+00,
          1.25516358e-01],
       [ -8.99100000e-02,   1.10107994e-17,   1.28833396e+00,
          1.30757249e-01]])

In [14]:
B_III_data[:,2:] - B_III_data_tmm[:,2:]

array([[  1.56912581e-03,  -2.92012654e-06],
       [  1.57241893e-03,   1.07222517e-05],
       [  1.57588007e-03,   2.38239604e-05],
       ..., 
       [  2.38102610e-03,  -7.85454235e-05],
       [  2.38377101e-03,  -3.81918781e-05],
       [  2.38680976e-03,   2.65248509e-06]])