In [1]:
B_HIGH_FILENAME = "B_high.txt"
B_LOW_FILENAME = "B_low.txt"

MAIN_RESULTS_FILENAME = "COMSOL Main Results.txt"

MAGNETIC_PROFILE_FILENAME = "COMSOL Magnetic Profile.txt"

COMSOL_PARAMETER_FILENAME = "params.txt"

In [2]:
import numpy as np

Load the high and low field data:

In [14]:
B_h = np.loadtxt(B_HIGH_FILENAME,skiprows=9)
B_h

array([[  3.70795097e-02,   3.35426589e-02,   6.79921079e-01],
       [  3.88101783e-02,   3.15241187e-02,   8.02806723e-01],
       [  3.95096690e-02,   3.37468663e-02,   6.47266282e-01],
       [  3.53553391e-02,   3.53553391e-02,   5.82056154e-01],
       [  3.78867932e-02,   3.51989470e-02,   5.09235881e-01],
       [  3.72110937e-02,   3.72110937e-02,   3.29931839e-01],
       [  4.04312050e-02,   2.94162823e-02,   9.44589476e-01],
       [  4.11858051e-02,   3.17140143e-02,   8.09658077e-01],
       [  3.94954360e-02,   3.94954360e-02,   3.52431996e-01],
       [  4.00845782e-02,   3.65050147e-02,   4.88238265e-01],
       [  4.19378820e-02,   2.72252467e-02,   1.10720379e+00],
       [  4.27871945e-02,   2.96220759e-02,   9.65614170e-01],
       [  4.33012702e-02,   2.50000000e-02,   1.47531505e+00],
       [  4.42803124e-02,   2.74620630e-02,   1.12856273e+00],
       [  4.20163770e-02,   4.20163770e-02,   4.05626740e-01],
       [  4.26802772e-02,   3.89354104e-02,   5.1067600

In [15]:
B_l = np.loadtxt(B_LOW_FILENAME,skiprows=9)
B_l

array([[  5.61257885e-18,   7.00000000e-02,   2.14891927e-04],
       [  6.55403828e-18,   6.61175521e-02,   3.00570389e-04],
       [  2.62341154e-03,   6.72713224e-02,   3.91717888e-04],
       [  6.15116578e-18,   6.20533490e-02,   8.25510631e-04],
       [  3.01956340e-03,   6.39312935e-02,   7.29702677e-04],
       [  5.74828664e-18,   5.79890787e-02,   1.22771293e-03],
       [  3.30512644e-03,   5.98333855e-02,   1.18012836e-03],
       [  5.34540815e-18,   5.39248151e-02,   1.42048220e-03],
       [  3.12565330e-03,   5.58652093e-02,   1.43735796e-03],
       [  5.99152602e-18,   5.00000000e-02,   1.41897370e-03],
       [  2.45577813e-03,   5.25820757e-02,   1.45452841e-03],
       [  4.04375395e-03,   4.98362123e-02,   1.43456547e-03],
       [  3.98652304e-03,   6.98863909e-02,   5.72591511e-04],
       [  8.90897813e-03,   4.91998995e-02,   1.73297610e-03],
       [  6.92315065e-03,   5.33395365e-02,   1.77019154e-03],
       [  8.90355215e-03,   6.94314537e-02,   1.3170346

In [27]:
B_h.shape

(131, 3)

In [28]:
B_l.shape

(74, 3)

Join the above data to build up the first quadrant of the air gap

In [29]:
B_1q = np.concatenate((B_h,B_l),axis=0)

In [30]:
B_1q

array([[  3.70795097e-02,   3.35426589e-02,   6.79921079e-01],
       [  3.88101783e-02,   3.15241187e-02,   8.02806723e-01],
       [  3.95096690e-02,   3.37468663e-02,   6.47266282e-01],
       [  3.53553391e-02,   3.53553391e-02,   5.82056154e-01],
       [  3.78867932e-02,   3.51989470e-02,   5.09235881e-01],
       [  3.72110937e-02,   3.72110937e-02,   3.29931839e-01],
       [  4.04312050e-02,   2.94162823e-02,   9.44589476e-01],
       [  4.11858051e-02,   3.17140143e-02,   8.09658077e-01],
       [  3.94954360e-02,   3.94954360e-02,   3.52431996e-01],
       [  4.00845782e-02,   3.65050147e-02,   4.88238265e-01],
       [  4.19378820e-02,   2.72252467e-02,   1.10720379e+00],
       [  4.27871945e-02,   2.96220759e-02,   9.65614170e-01],
       [  4.33012702e-02,   2.50000000e-02,   1.47531505e+00],
       [  4.42803124e-02,   2.74620630e-02,   1.12856273e+00],
       [  4.20163770e-02,   4.20163770e-02,   4.05626740e-01],
       [  4.26802772e-02,   3.89354104e-02,   5.1067600

Calculate a vector of angular values for the first quadrant

Calculate a matrix of $(r,\phi)$ points  along the first quadrant where to evaluate the field (in this controlled grid), and interpolate from the previous array (where each row corresponde to a radial chord i.e. a single value of $\phi$)

Calculate the average value along each radial chord