$$
\newcommand{\ped}[1]{_{\mathrm{#1}}}
\newcommand{\ap}[1]{^{\mathrm{#1}}}
\newcommand{\nvector}[1]{\mathbf{#1}}
\newcommand{\nmatrix}[1]{\mathit{#1}}
\newcommand{\unitvector}[1]{\hat{\nvector{e}}_{#1}}
\newcommand{\volume}{\mathcal{V}}
\newcommand{\average}[1]{\overline{#1}}
\newcommand{\rate}[1]{\dot{#1}}
\newcommand{\flux}[1]{{#1}''}
\newcommand{\curl}[1]{\nabla\times {#1}}
\newcommand{\curlv}[1]{\curl{\nvector{#1}}}
\newcommand{\divergent}[1]{\nabla \cdot #1}
\newcommand{\divergentv}[1]{\divergent{\nvector{#1}}}
\newcommand{\divergentpar}[1]{\divergent{\left( #1 \right)}}
\newcommand{\gradient}[1]{\nabla {#1}}
\newcommand{\gradientpar}[1]{\gradient{\left( {#1} \right)}}
\newcommand{\laplacian}[1]{\nabla^2 #1}
\newcommand{\laplacianpar}[1]{\laplacian{\left( #1 \right)}}
\newcommand{\vectornorm}[1]{\left\lVert #1 \right\rVert}
\newcommand{\diffp}[2]{\frac{\partial {#1}}{\partial {#2}}}
\newcommand{\diffps}[2]{\frac{\partial^2 {#1}}{\partial {#2}^2}}
\newcommand{\rvec}{\nvector{r}}
\newcommand{\nvh}{\nvector{H}}
\newcommand{\nvb}{\nvector{B}}
\newcommand{\nvrem}{\nvector{B}\ped{rem}}
\newcommand{\nvbrem}{\nvrem}
\newcommand{\nvm}{\nvector{M}}
\newcommand{\mur}{\mu\ped{r}}
\newcommand{\nvbremhat}{\hat{\nvector{B}}\ped{rem}}
\newcommand{\acoef}[2]{a_{{#1},\mathrm{#2}}}
\newcommand{\bcoef}[2]{b_{{#1},\mathrm{#2}}}
\newcommand{\Azexpr}[1]{A_{\mathrm{#1}\, z}}
\newcommand{\bremii}{B_{\mathrm{rem,II}}}
\newcommand{\bremiv}{B_{\mathrm{rem,IV}}}
\newcommand{\aIII}{\acoef{1}{III}}
\newcommand{\bIII}{\bcoef{1}{III}}
\newcommand{\nvbIII}{\nvector{B}\ped{III}}
\newcommand{\BIII}{B\ped{III}}
\newcommand{\diffd}[1]{\mathrm{d}\,{#1}}
$$

# Demonstration of the principle of superposition

Teslamax model:

<img src="figures/teslamax.png" width=500>

Tell the location of the TeslaMax Java class file:

In [1]:
from pathlib import Path
import os
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import teslamax
from teslamax import TeslaMaxModel



mpl_params = {'text.usetex': True,
              'font.family': 'serif',
              'font.serif': 'Computer Modern',
              'text.latex.preamble': [r'\usepackage{engsymbols}',
                                      r'\usepackage{magref}',
                                      r'\usepackage{siunitx}']}
matplotlib.rcParams.update(mpl_params)


In [2]:
FIGSIZE_CM = 20
FIGSIZE_INCHES = FIGSIZE_CM / 2.54

FONTSIZE = 20

## Playground

In [3]:
os.chdir('C:\\Users\\fabiofortkamp\\code\\TeslaMax\\')

In [4]:
teslamax_playground = "teslamax-play"


In [5]:
os.getcwd()

'C:\\Users\\fabiofortkamp\\code\\TeslaMax'

We wish to demonstrate the Principle of Superposition to the TeslaMax model.

We define a sample geometry, with only one segment in each cylinder.

In [6]:
param_dict = {"R_i": 0.015,
                "R_o": 0.070,
                "h_gap": 0.020,
                "R_s": 0.140,
                "h_fc": 0.010,
                "R_e": 2,
                "n_IV": 1,
                "alpha_rem_IV_1": 15,
                "phi_S_IV": 45,
                "n_II": 1,
                "alpha_rem_II_1": 15,
                "phi_C_II": 0,
                "phi_S_II": 45,
                "B_rem_II_1": 1.4,
                "mu_r_II": 1.05,
                "B_rem_IV_1": 1.4,
                "mu_r_IV": 1.05,
                "linear_iron": 1,
                "mu_r_iron": 5e3,
             }



We "run" the TeslaMax model:

In [7]:
tmm = TeslaMaxModel(params=param_dict,
                   path=teslamax_playground)

In [8]:
tmm.run()

We define an arbitrary point in the air gap region

In [9]:
x_gap = param_dict["R_o"] + 0.5 * param_dict["h_gap"]
y_gap = 0
point_gap = np.array([x_gap,y_gap])

Then we calculate the value of $\nvb$ in the air gap at that position:

In [10]:
B_total = tmm.calculate_B_III_from_position(point_cartesian=point_gap)[0]
B_total

array([  1.06990814e+00,   9.56114463e-04])

In the `teslamax` library, there is a function which performs a FEM simulation to calculate the $\nvector{F}^B_{\mathrm{rem},m,k}$ operator, which represents the contribution of segment $k$ in magnet $m$ to the magnetic flux density in the air gap.

With this function we can calculate te contribution of the only segment in magnet IV, passing the properties of the above dictionary. Notice that because `param_dict` defines one segment in each magnet, this cell below will nulify the remanence of magnet II:

In [11]:
B_outer = teslamax.calculate_B_III_from_single_block(point=point_gap,
                                           angle=param_dict["alpha_rem_IV_1"],
                                           magnet='IV',
                                           magnitude=param_dict["B_rem_IV_1"],
                                           params=param_dict,
                                            segment=1)[0]
B_outer

array([  6.72249900e-01,   4.11653477e-04])

In [12]:
param_dict

{'B_rem_II_1': 1.4,
 'B_rem_IV_1': 1.4,
 'R_e': 2,
 'R_i': 0.015,
 'R_o': 0.07,
 'R_s': 0.14,
 'alpha_rem_II_1': 15,
 'alpha_rem_IV_1': 15,
 'h_fc': 0.01,
 'h_gap': 0.02,
 'linear_iron': 1,
 'mu_r_II': 1.05,
 'mu_r_IV': 1.05,
 'mu_r_iron': 5000.0,
 'n_II': 1,
 'n_IV': 1,
 'phi_C_II': 0,
 'phi_S_II': 45,
 'phi_S_IV': 45}

Now we do the same, but calculating the effect of the single block in the inner magnet:

In [13]:
B_inner = teslamax.calculate_B_III_from_single_block(point=point_gap,
                                           angle=param_dict["alpha_rem_II_1"],
                                           magnet='II',
                                           magnitude=param_dict["B_rem_II_1"],
                                           params=param_dict,
                                            segment=1)[0]
B_inner

array([ 0.39766033,  0.00054446])

The total field should be the sum of the "partial" fields calculated below:

In [14]:
B_total - (B_outer + B_inner)

array([ -2.08717953e-06,   5.34604564e-09])

Notice that this is not exactly zero due to interpolation errors (since for each condition that is a mesh generation, and an interpolation scheme to find the field at the desired point). However, in relation to the total field:

In [16]:
(B_total - (B_outer + B_inner))/B_total * 100 #in percentage


array([-0.00019508,  0.00055914])